# Generated by Django 4.2.2 on 2023-07-04 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('related_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_user_real_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='related_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_doc', to='v1.extendeduser', verbose_name='related_user'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='related_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_patient', to='v1.extendeduser', verbose_name='related_user'),
        ),
        migrations.AlterField(
            model_name='support',
            name='cor_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_doc', to='v1.extendeduser', verbose_name='related_user'),
        ),
    ]
