# Generated by Django 4.2.2 on 2023-07-04 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_remove_document_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='treatmentrequest',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.treatmentrequeststatus'),
        ),
        migrations.AlterField(
            model_name='treatmentrequest',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='viza',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.vizastatus'),
        ),
    ]
