# Generated by Django 4.2.2 on 2023-07-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_alter_paymentrequest_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_class', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='package',
            old_name='estimate_cost',
            new_name='estimated_cost',
        ),
        migrations.AddField(
            model_name='package',
            name='package_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.packageclass', verbose_name='package_class'),
        ),
    ]
