# Generated by Django 4.2.2 on 2023-07-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_packageclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.packageclass', verbose_name='package_class'),
        ),
    ]
