# Generated by Django 4.2.2 on 2023-07-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_treatmentrequest_reserved_hotel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentrequest',
            old_name='reserved_hotel_id',
            new_name='reserved_hotel',
        ),
    ]
