# Generated by Django 4.2.2 on 2023-07-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_sysadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='VizaRequirement',
            fields=[
                ('requirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.requirement')),
            ],
            bases=('v1.requirement',),
        ),
        migrations.RemoveField(
            model_name='treatmentrequest',
            name='related_viza',
        ),
        migrations.RemoveField(
            model_name='viza',
            name='id',
        ),
        migrations.AddField(
            model_name='viza',
            name='serial_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viza',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viza',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viza',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_user', to='v1.patient', verbose_name='related_user'),
        ),
        migrations.CreateModel(
            name='VizaDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.document')),
                ('related_visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.viza', verbose_name='related_visa')),
            ],
            bases=('v1.document',),
        ),
    ]
