# Generated by Django 4.2.2 on 2023-07-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_vizarequirement_remove_treatmentrequest_related_viza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viza',
            name='serial_no',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
