# Generated by Django 4.2.2 on 2023-07-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_alter_paymentrequest_verified_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='cor_user',
            new_name='related_user',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.city'),
        ),
        migrations.AddField(
            model_name='support',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentrequest',
            name='related_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.support', verbose_name='related_support'),
        ),
    ]
