# Generated by Django 4.2.2 on 2023-07-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0018_rename_cor_user_support_related_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.city'),
        ),
    ]
