# Generated by Django 4.2.2 on 2023-07-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0021_alter_viza_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viza',
            name='status',
        ),
    ]
