# Generated by Django 4.2.2 on 2023-07-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_extendeduser_alter_doctor_related_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AlterField(
            model_name='treatmentrequest',
            name='related_documents',
            field=models.ManyToManyField(blank=True, null=True, to='v1.document', verbose_name='related_documents'),
        ),
    ]
