# Generated by Django 4.2.2 on 2023-07-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_alter_viza_request_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
