# Generated by Django 4.2.2 on 2023-07-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0022_remove_viza_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='viza',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.vizastatus'),
        ),
    ]
